<%@ Page Title="AddPost" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="AddPost.aspx.cs" Inherits="LocalTheatre.Admin.AddPost" %>
<asp:Content ID="Content1" 
 ContentPlaceHolderID="MainContent" runat="server"> 
    <asp:GridView ID="grdPosts" runat="server" Width="235px" 
        CellPadding="4" ForeColor="Black" GridLines="Vertical"
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True"
        DataKeyNames="PostId" BackColor="White" BorderColor="#DEDFDE" 
        BorderStyle="None" BorderWidth="1px" CssClass="table"
        OnRowDeleting="GrdPosts_RowDeleting" 
        OnRowEditing="GrdPosts_RowEditing" 
        OnSelectedIndexChanged="GrdPosts_SelectedIndexChanged"
        OnRowCancelingEdit="grdPosts_RowCancelingEdit"
        OnRowUpdating="GrdPosts_RowUpdating">
        <AlternatingRowStyle BackColor="White" />
        <Columns>
            <asp:TemplateField></asp:TemplateField>
        </Columns>

            
                


        <FooterStyle BackColor="#CCCC99" />
        <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
        <RowStyle BackColor="#F7F7DE" />
        <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
        <SortedAscendingCellStyle BackColor="#FBFBF2" />
        <SortedAscendingHeaderStyle BackColor="#848384" />
        <SortedDescendingCellStyle BackColor="#EAEAD3" />
        <SortedDescendingHeaderStyle BackColor="#575357" />

            
                


        </asp:GridView>
    <br />
    
    <asp:Label ID="lblTitle" CssClass="label label-default" runat="server" Text="Title"></asp:Label>
    <br />
    <asp:TextBox ID="tbTitle"  runat="server"></asp:TextBox>
   <br />
    <asp:Label ID="lblCategory" CssClass="label label-default" runat="server" Text="Category"></asp:Label>
    <br />
    <div class="dropdown">
    <asp:DropDownList ID="ddlCategories" runat="server"
        DataSourceID="LinqDataSource1" 
        DataTextField="Type" DataValueField="CategoryId">
        <asp:ListItem class="dropdown-item">1</asp:ListItem>
        <asp:ListItem class="dropdown-item">2</asp:ListItem>
    </asp:DropDownList></div>
    <asp:LinqDataSource ID="LinqDataSource1" runat="server" 
        ContextTypeName="LocalTheatre.Models.ApplicationDbContext"
        EntityTypeName="" Select="new (CategoryId, Type)" 
        TableName="Categories">
    </asp:LinqDataSource>
    <br />
    <asp:Label ID="lblPost" CssClass="label label-default" runat="server" Text="Post"></asp:Label>
    <br />
    <asp:TextBox ID="tbPost" class="form-control"  runat="server"></asp:TextBox>
    <br />
    <asp:Label ID="lblusername" CssClass="label label-default" runat="server" Text="username"></asp:Label>
    <br />
    <asp:TextBox ID="tbUsername"  runat="server" Enabled="False"></asp:TextBox>
<br />
    

   

    <asp:Button ID="btnAddPost" runat="server" CssClass="btn"
        OnClick="AddAPost_Click" Text="Add Post" />
    <br />
    

   

</asp:Content>
