<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="RolesAdmin.aspx.cs" Inherits="LocalTheatre.Admin.RolesAdmin" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div>
        <h2>Roles Admin</h2>
        <br />
        <asp:Label ID="lblRole" CssClass="badge" Text="Add a role" runat="server"></asp:Label>
        <br />
        <asp:TextBox ID="txtRole" CssClass="text" runat="server"></asp:TextBox>
       <br />
        <asp:Button ID="btnRole" CssClass="btn" Text="Add Role" runat="server" OnClick="btnRole_Click" />
        <br />
        <asp:Label ID="lblErrorMessage" CssClass="label label-warning" runat="server"></asp:Label>
    </div>
    
    <div>
        <asp:GridView ID="grdRoles" DataKeyNames="Id" CssClass="table" runat="server"
            AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
            AutoGenerateEditButton="True" OnRowCancelingEdit="grdRoles_RowCancelingEdit"
            OnRowDeleting="grdRoles_RowDeleting" OnRowEditing="grdRoles_RowEditing"
            OnRowUpdating="grdRoles_RowUpdating" CellPadding="4" ForeColor="#333333" GridLines="None">
            <AlternatingRowStyle BackColor="White" />
            <Columns>
                <asp:BoundField DataField="Name" HeaderText="Role" SortExpression="Name" />
            </Columns>
            <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
            <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
            <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
            <SortedAscendingCellStyle BackColor="#FDF5AC" />
            <SortedAscendingHeaderStyle BackColor="#4D0000" />
            <SortedDescendingCellStyle BackColor="#FCF6C0" />
            <SortedDescendingHeaderStyle BackColor="#820000" />
        </asp:GridView>
        
    </div>
</asp:Content>
