<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="UserAdmin.aspx.cs" Inherits="LocalTheatre.Admin.UserAdmin" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <asp:GridView ID="gridViewUser" CssClass="table-responsive" 
        DataKeyNames="Id" Caption="User Administration" 
        AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" 
        runat="server" AutoGenerateColumns="False" 
        OnRowDataBound="GridViewUser_RowDataBound" 
        OnRowDeleting="GridViewUser_RowDeleting" 
        OnRowEditing="GridViewUser_RowEditing" 
        OnRowUpdating="GridViewUser_RowUpdating" 
        OnRowCancelingEdit="GridViewUser_RowCancelingEdit">
        <Columns>
            <asp:BoundField DataField="UserName" HeaderText="Username" 
                SortExpression="Username" />
            <asp:BoundField DataField="Email"
                HeaderText="Email" SortExpression="Email" />
            <asp:BoundField DataField="Id"  
                HeaderText="Id"  
                SortExpression="Id" Visible="False"/>

            <asp:TemplateField HeaderText="Roles">
                <ItemTemplate>
                <asp:GridView ID="GridViewRoles" runat="server" AutoGenerateDeleteButton="true"
                    AutoGenerateEditButton="true" OnRowDeleting="GridViewRoles_RowDeleting"
                    OnRowEditing="GridViewRoles_RowEditing" 
                    OnRowUpdating="GridViewRoles_RowUpdating"
                    OnRowCancellingEdit="GridViewRoles_RowCancelingEdit" >
                    <Columns>
                    <asp:TemplateField>
                        <EditItemTemplate>
                    <asp:DropDownList ID="DropDownList1" DataTextField="Name" DataValueField="Name" DataSourceID="LinqDataSource1" runat="server">
                    </asp:DropDownList>
                            <asp:LinqDataSource ID="LinqDataSource1"
                                ContextTypeName="LocalTheatre.Models.ApplicationDbContext"
                                EntityTypeName="" Select="new (Name)" TableName="Roles"
                                runat="server"></asp:LinqDataSource>
                        </EditItemTemplate>
                    </asp:TemplateField>
                                   
                    </Columns>
                </asp:GridView>
                </ItemTemplate>
            </asp:TemplateField>
            

        </Columns>
    </asp:GridView>
</asp:Content>
