<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Blog.aspx.cs" Inherits="LocalTheatre.Blog" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent"  runat="server"><title><%: Page.Title %> - My Local Theatre Blog Posts</title> <br /><div> <h1> Welcome to the blog! </h1>


        <br />

        <asp:GridView ID="GridView1" runat="server" DataKeyNames="PostId" 
            AutoGenerateColumns="False" Width="100%" CellPadding="4"
            ForeColor="#333333" GridLines="None" 
            CssClass="table-responsive" ShowFooter="True" 
            OnRowDataBound="GridView1_RowDataBound">
            <AlternatingRowStyle BackColor="White" />
            <Columns>
                <asp:TemplateField>
                    
                    <ItemTemplate>
                        <asp:Label ID="lblPostId" runat="server" 
                            class="badge" Text='<%# Eval("PostId") %>'></asp:Label> 
                        <asp:Label ID="lblUserId" runat="server" 
                            class="badge" Text='<%# Eval("UserId") %>'></asp:Label>
                        <br />
                        <asp:Label class="badge" ID="lblDate" runat="server"  
                            Text='<%# Eval("Date") %>'></asp:Label>
                        <br />
                        <br />
                        <asp:Label class="badge" ID="lblTitle" runat="server" 
                             Text='<%# Eval("Title") %>'></asp:Label>
                        <br />
                        <br />
                        <asp:Label class="sucess" ID="lblText" runat="server" 
                            Text='<%# Eval("Text") %>' ></asp:Label>
                        <br />
                        <br />
                        <br />
                        
                        <asp:GridView ID="grdComments" 
                            AlternatingRowStyle-CssClass="table" runat="server" 
                            AutoGenerateColumns="False" CssClass="table-responsive" 
                            AutoGenerateDeleteButton="True"
                            OnRowDeleting="grdComments_RowDeleting"
                            
                            DataKeyNames="CommentId">

                        <Columns>
                            
                            <asp:BoundField DataField="userId"  HeaderText="Username"/>
                            
                            <asp:BoundField DataField="Date" HeaderText="Date" SortExpression="Date" />
                            <asp:BoundField DataField="Text" HeaderText="Text" SortExpression="Text" />
                          
                        </Columns>
                        </asp:GridView>
                        <asp:LinkButton ID="lnkShowAddComment" cssClass="btn" runat="server"
                            OnClick="lnkShowAddComment_Click">Add A Comment
                                                    </asp:LinkButton>
                        <asp:Panel ID="pnlComment" Visible="false" runat="server">
                            <asp:TextBox ID="txtComment" runat="server" CssClass="form-control" TextMode="MultiLine"></asp:TextBox>
                            <asp:Button ID="btnSubmitComment" runat="server" Text="Add" OnClick="btnSubmitComment_Click" />
                          </asp:Panel>
                         
                     
                    </ItemTemplate>
                </asp:TemplateField>
                
            </Columns>

            <EmptyDataTemplate>
                <asp:Label ID="lblEmptyDataTemplate" CssClass="badge" runat="server" Text="No data to show"></asp:Label>
            </EmptyDataTemplate>

            <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
            <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
            <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
            <SortedAscendingCellStyle BackColor="#FDF5AC" />
            <SortedAscendingHeaderStyle BackColor="#4D0000" />
            <SortedDescendingCellStyle BackColor="#FCF6C0" />
            <SortedDescendingHeaderStyle BackColor="#820000" />

        </asp:GridView>
    </div>
</asp:Content>
